### ISSUE TITLE
Error when bot is not in channel and tries to use `say`

### ISSUE THREAD

**Issue by connorads** [connorads/lockbot#11]
![image](https://user-images.githubusercontent.com/10026538/82506647-434e6700-9af8-11ea-81d5-cc7eaf5f7de1.png)

```
bolt-app Error: An API error occurred: not_in_channel
    at Object.platformErrorFromResult (/var/task/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/var/task/node_modules/@slack/web-api/dist/WebClient.js:486:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async respond (/var/task/src/index.js:24:17)
    at async /var/task/src/index.js:53:5
    at async Array.<anonymous> (/var/task/node_modules/@slack/bolt/dist/middleware/builtin.js:203:9)
    at async Array.exports.onlyCommands (/var/task/node_modules/@slack/bolt/dist/middleware/builtin.js:39:5) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'not_in_channel',
    response_metadata: { scopes: [Array], acceptedScopes: [Array] }
  }
}
```

**Comment by connorads** [comment]
https://api.slack.com/authentication/basics#public

**Comment by connorads** [comment]
Added scope https://api.slack.com/scopes/chat:write.public

**Comment by connorads** [comment]
Issue still needs to be handled for private channels

**Comment by connorads** [comment]
Don't need the extra scope, just use `respond` appropriately
https://slack.dev/bolt-js/concepts#action-respond
